title: santaclz's blog
email: rabit0110115@gmail.com
description: >-
  Vulnerability researcher's blog focusing on system internals, 
  reverse engineering and exploitation.
baseurl: ""
url: "https://santaclz.github.io"
twitter_username: santaclzz
github_username: santaclz

markdown: kramdown
remote-theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: G-DXDH6RMJMS

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

